// Generated by scripts/generate-user-workflow-cli-tools.mjs. Edit its authoring definitions.
import { readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';

export const revision = "1.0.5";
const cli = "gcloud";
const environment = {
  "CLOUDSDK_CORE_DISABLE_PROMPTS": "1",
  "CLOUDSDK_CORE_DISABLE_USAGE_REPORTING": "true",
  "PAGER": "cat",
  "NO_COLOR": "1"
};
const failureDiagnostic = null;
// Generated from Valdr packages/util/src/redaction.ts; refresh via the CLI generator.
const SENSITIVE_VALUE_PATTERN = /\b(?:sk|pk|rk)[_-][a-z0-9._-]{16,}|\b(?:gh[pousr]|github_pat|xox[baprs]?)[_-][a-z0-9._-]{12,}|\b(?:ctx7|ya29)[a-z0-9._-]{12,}/gi;
const SENSITIVE_ASSIGNMENT_PATTERN = /(\b[\w.-]*(?:api[_-]?key|access[_-]?key|private[_-]?key|token|secret|authorization|password|credential)[\w.-]*\b\s*[:=]\s*)(?:"[^"]*"|'[^']*'|bearer\s+[^\s,;]+|[^\s,;]+)/gi;
const BEARER_VALUE_PATTERN = /(\bbearer\s+)[^\s,;]+/gi;
const redactSensitiveText = (value, knownSecrets = []) => {
  if (value.length === 0) {
    return value;
  }
  let scrubbed = value;
  for (const secret of new Set(knownSecrets)) {
    if (secret && secret !== "[REDACTED]")
      scrubbed = scrubbed.replaceAll(secret, "[REDACTED]");
  }
  const keyValuePattern = /("([^"]*(?:api[_-]?key|access[_-]?key|private[_-]?key|token|secret|authorization|auth|password|credential)[^"]*)"\s*:\s*")([^"]+)(")/gi;
  return scrubbed.replace(keyValuePattern, "$1[REDACTED]$4").replace(SENSITIVE_ASSIGNMENT_PATTERN, "$1[REDACTED]").replace(BEARER_VALUE_PATTERN, "$1[REDACTED]").replace(SENSITIVE_VALUE_PATTERN, "[REDACTED]");
};

export const commands = {
  "version": {
    "path": [
      "version"
    ],
    "description": "Read the installed CLI version without signing in.",
    "argv": [
      "version"
    ],
    "text": true,
    "properties": {},
    "required": []
  },
  "projects-list": {
    "path": [
      "projects",
      "list"
    ],
    "description": "List at most 100 visible projects.",
    "argv": [
      "projects",
      "list",
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      {
        "input": "filter",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096
        },
        "flag": "--filter",
        "required": false
      },
      {
        "input": "project",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
        },
        "flag": "--project",
        "required": false
      },
      "--format=json",
      "--quiet"
    ],
    "properties": {
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      },
      "filter": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4096
      },
      "project": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
      }
    },
    "required": []
  },
  "projects-describe": {
    "path": [
      "projects",
      "describe"
    ],
    "description": "Read one project.",
    "argv": [
      "projects",
      "describe",
      {
        "input": "projectId",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
        },
        "required": true
      },
      {
        "input": "project",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
        },
        "flag": "--project",
        "required": false
      },
      "--format=json",
      "--quiet"
    ],
    "properties": {
      "projectId": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
      },
      "project": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
      }
    },
    "required": [
      "projectId"
    ]
  },
  "compute-instances-list": {
    "path": [
      "compute",
      "instances",
      "list"
    ],
    "description": "List at most 100 compute instances in the selected or configured project.",
    "argv": [
      "compute",
      "instances",
      "list",
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      {
        "input": "filter",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096
        },
        "flag": "--filter",
        "required": false
      },
      {
        "input": "project",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
        },
        "flag": "--project",
        "required": false
      },
      "--format=json",
      "--quiet"
    ],
    "properties": {
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      },
      "filter": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4096
      },
      "project": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
      }
    },
    "required": []
  },
  "compute-instances-describe": {
    "path": [
      "compute",
      "instances",
      "describe"
    ],
    "description": "Read one compute instance in an explicit zone.",
    "argv": [
      "compute",
      "instances",
      "describe",
      {
        "input": "instance",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
        },
        "required": true
      },
      {
        "input": "zone",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
        },
        "flag": "--zone",
        "required": true
      },
      {
        "input": "project",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
        },
        "flag": "--project",
        "required": false
      },
      "--format=json",
      "--quiet"
    ],
    "properties": {
      "instance": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
      },
      "zone": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
      },
      "project": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
      }
    },
    "required": [
      "instance",
      "zone"
    ]
  },
  "compute-disks-list": {
    "path": [
      "compute",
      "disks",
      "list"
    ],
    "description": "List at most 100 block storage disks.",
    "argv": [
      "compute",
      "disks",
      "list",
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      {
        "input": "filter",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096
        },
        "flag": "--filter",
        "required": false
      },
      {
        "input": "project",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
        },
        "flag": "--project",
        "required": false
      },
      "--format=json",
      "--quiet"
    ],
    "properties": {
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      },
      "filter": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4096
      },
      "project": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
      }
    },
    "required": []
  },
  "compute-networks-list": {
    "path": [
      "compute",
      "networks",
      "list"
    ],
    "description": "List at most 100 virtual networks.",
    "argv": [
      "compute",
      "networks",
      "list",
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      {
        "input": "filter",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096
        },
        "flag": "--filter",
        "required": false
      },
      {
        "input": "project",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
        },
        "flag": "--project",
        "required": false
      },
      "--format=json",
      "--quiet"
    ],
    "properties": {
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      },
      "filter": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4096
      },
      "project": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
      }
    },
    "required": []
  },
  "storage-buckets-list": {
    "path": [
      "storage",
      "buckets",
      "list"
    ],
    "description": "List at most 100 storage buckets.",
    "argv": [
      "storage",
      "buckets",
      "list",
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      {
        "input": "filter",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096
        },
        "flag": "--filter",
        "required": false
      },
      {
        "input": "project",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
        },
        "flag": "--project",
        "required": false
      },
      "--format=json",
      "--quiet"
    ],
    "properties": {
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      },
      "filter": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4096
      },
      "project": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
      }
    },
    "required": []
  },
  "run-services-list": {
    "path": [
      "run",
      "services",
      "list"
    ],
    "description": "List at most 100 Cloud Run services.",
    "argv": [
      "run",
      "services",
      "list",
      {
        "input": "region",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
        },
        "flag": "--region",
        "required": false
      },
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      {
        "input": "filter",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096
        },
        "flag": "--filter",
        "required": false
      },
      {
        "input": "project",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
        },
        "flag": "--project",
        "required": false
      },
      "--format=json",
      "--quiet"
    ],
    "properties": {
      "region": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
      },
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      },
      "filter": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4096
      },
      "project": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
      }
    },
    "required": []
  },
  "run-services-describe": {
    "path": [
      "run",
      "services",
      "describe"
    ],
    "description": "Read one Cloud Run service in an explicit region.",
    "argv": [
      "run",
      "services",
      "describe",
      {
        "input": "service",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
        },
        "required": true
      },
      {
        "input": "region",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
        },
        "flag": "--region",
        "required": true
      },
      {
        "input": "project",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
        },
        "flag": "--project",
        "required": false
      },
      "--format=json",
      "--quiet"
    ],
    "properties": {
      "service": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
      },
      "region": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
      },
      "project": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[a-z][a-z0-9-]{4,61}[a-z0-9]$"
      }
    },
    "required": [
      "service",
      "region"
    ]
  }
};
export function commandFor(actionId, input) {
  const spec = Object.hasOwn(commands, actionId) ? commands[actionId] : void 0;
  if (!spec)
    throw Error("Unsupported CLI action.");
  if (!input || typeof input !== "object" || Array.isArray(input))
    throw Error("Input must be an object.");
  if (Object.keys(input).some((key) => !Object.hasOwn(spec.properties, key)) || spec.required.some((key) => !Object.hasOwn(input, key)))
    throw Error("Unexpected or missing input field.");
  for (const [key, value] of Object.entries(input)) {
    const s = spec.properties[key];
    if (!(s.type === "integer" ? Number.isInteger(value) && value >= s.minimum && value <= s.maximum : typeof value === "string" && !value.includes("\x00") && (s.minLength === void 0 || [...value].length >= s.minLength) && (s.maxLength === void 0 || [...value].length <= s.maxLength) && (!s.pattern || new RegExp(s.pattern).test(value)) && (!s.enum || s.enum.includes(value))))
      throw Error(`Invalid input field: ${key}.`);
  }
  return { args: spec.argv.flatMap((binding) => {
    if (typeof binding === "string")
      return [binding];
    const value = input[binding.input] ?? binding.default;
    if (value === void 0)
      return [];
    return binding.flag ? [`${binding.flag}=${value}`] : [String(value)];
  }), text: spec.text === !0 };
}
function diagnosticText(result, secrets, limit) {
  if (result.error)
    return `CLI diagnostic unavailable (${result.error.code ?? "capture_failed"}).`;
  const redacted = redactSensitiveText(result.stderr ?? "", secrets).trim();
  return redacted.length > limit ? `${redacted.slice(0, limit)}\u2026 [truncated]` : redacted;
}
function main() {
  const fail = (code, message, termination = {}) => ({ ok: !1, error: { code, message, ...termination } });
  try {
    const bytes = readFileSync(0);
    if (bytes.length > 65536)
      return fail("invalid_input", "Request exceeds 65536 bytes.");
    const request = JSON.parse(bytes.toString("utf8")), allowed = ["protocolVersion", "toolId", "toolRevision", "action", "input", "operationId", "attemptId"];
    if (!request || request.protocolVersion !== 1 || request.toolId !== `valdr-tools.user.${cli}` || request.toolRevision !== revision || !["operationId", "attemptId"].every((key) => typeof request[key] === "string" && request[key].length > 0) || Object.keys(request).some((key) => !allowed.includes(key)))
      return fail("invalid_request", "Invalid user-tool request envelope.");
    const command = commandFor(request.action, request.input), result = spawnSync(cli, command.args, {
      encoding: "utf8",
      shell: !1,
      timeout: 25000,
      maxBuffer: 524288,
      env: { ...process.env, ...environment },
      stdio: ["ignore", "pipe", "pipe"]
    });
    if (result.error?.code === "ENOENT")
      return fail("runtime_missing", `${cli} is not installed on the host PATH.`);
    if (result.error || result.status !== 0) {
      const secrets = Object.entries(process.env).filter(([key]) => /api[_-]?key|access[_-]?key|private[_-]?key|token|secret|authorization|auth|password|credential/i.test(key)).map(([, value]) => value).filter(Boolean), details = [`${cli} failed (${result.error?.code ?? result.status ?? result.signal}).`];
      if (!result.error && failureDiagnostic && failureDiagnostic.actionPathPrefix.every((part, index) => commands[request.action].path[index] === part)) {
        const probe = spawnSync(cli, failureDiagnostic.args, { encoding: "utf8", shell: !1, timeout: 5000, maxBuffer: 16384, env: { ...process.env, ...environment }, stdio: ["ignore", "ignore", "pipe"] });
        if (probe.error || probe.status !== 0)
          details.push(`Authentication diagnostic: ${diagnosticText(probe, secrets, 600) || `status check failed (${probe.error?.code ?? probe.status ?? probe.signal}).`}`);
      }
      details.push(diagnosticText(result, secrets, 1200));
      return fail("cli_failed", details.filter(Boolean).join(`
`).slice(0, 2000), { exitCode: result.status, signal: result.signal });
    }
    try {
      return { ok: !0, data: command.text ? { version: result.stdout.trim() } : JSON.parse(result.stdout) };
    } catch {
      return fail("invalid_output", `${cli} did not return valid JSON.`);
    }
  } catch (error) {
    return fail("invalid_input", error instanceof SyntaxError ? "Request must be JSON." : error.message);
  }
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) process.stdout.write(JSON.stringify(main()) + '\n');
