// Generated by scripts/generate-user-workflow-cli-tools.mjs. Edit its authoring definitions.
import { readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';

export const revision = "1.0.6";
const cli = "acli";
const environment = {
  "PAGER": "cat",
  "NO_COLOR": "1"
};
const failureDiagnostic = {"actionPathPrefix":["jira"],"args":["jira","auth","status"]};
// Generated from Valdr packages/util/src/redaction.ts; refresh via the CLI generator.
const SENSITIVE_VALUE_PATTERN = /\b(?:sk|pk|rk)[_-][a-z0-9._-]{16,}|\b(?:gh[pousr]|github_pat|xox[baprs]?)[_-][a-z0-9._-]{12,}|\b(?:ctx7|ya29)[a-z0-9._-]{12,}/gi;
const SENSITIVE_ASSIGNMENT_PATTERN = /(\b[\w.-]*(?:api[_-]?key|access[_-]?key|private[_-]?key|token|secret|authorization|password|credential)[\w.-]*\b\s*[:=]\s*)(?:"[^"]*"|'[^']*'|bearer\s+[^\s,;]+|[^\s,;]+)/gi;
const BEARER_VALUE_PATTERN = /(\bbearer\s+)[^\s,;]+/gi;
const redactSensitiveText = (value, knownSecrets = []) => {
  if (value.length === 0) {
    return value;
  }
  let scrubbed = value;
  for (const secret of new Set(knownSecrets)) {
    if (secret && secret !== "[REDACTED]")
      scrubbed = scrubbed.replaceAll(secret, "[REDACTED]");
  }
  const keyValuePattern = /("([^"]*(?:api[_-]?key|access[_-]?key|private[_-]?key|token|secret|authorization|auth|password|credential)[^"]*)"\s*:\s*")([^"]+)(")/gi;
  return scrubbed.replace(keyValuePattern, "$1[REDACTED]$4").replace(SENSITIVE_ASSIGNMENT_PATTERN, "$1[REDACTED]").replace(BEARER_VALUE_PATTERN, "$1[REDACTED]").replace(SENSITIVE_VALUE_PATTERN, "[REDACTED]");
};

export const commands = {
  "version": {
    "path": [
      "version"
    ],
    "description": "Read the installed CLI version without signing in.",
    "argv": [
      "--version"
    ],
    "text": true,
    "properties": {},
    "required": []
  },
  "jira-workitem-view": {
    "path": [
      "jira",
      "workitem",
      "view"
    ],
    "description": "Read one Jira work item.",
    "argv": [
      "jira",
      "workitem",
      "view",
      {
        "input": "key",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Z][A-Z0-9_]*-[0-9]+$"
        },
        "required": true
      },
      "--json"
    ],
    "properties": {
      "key": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Z][A-Z0-9_]*-[0-9]+$"
      }
    },
    "required": [
      "key"
    ]
  },
  "jira-workitem-import": {
    "path": [
      "jira",
      "workitem",
      "import"
    ],
    "description": "Read one Jira work item normalized for task import, with its description as markdown.",
    "argv": [
      "jira",
      "workitem",
      "view",
      {
        "input": "key",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Z][A-Z0-9_]*-[0-9]+$"
        },
        "required": true
      },
      "--fields",
      "summary,issuetype,priority,labels,description,status",
      "--json"
    ],
    "transform": "jiraWorkitemImport",
    "properties": {
      "key": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Z][A-Z0-9_]*-[0-9]+$"
      }
    },
    "required": [
      "key"
    ]
  },
  "jira-workitem-search": {
    "path": [
      "jira",
      "workitem",
      "search"
    ],
    "description": "Read at most 100 work items matching JQL.",
    "argv": [
      "jira",
      "workitem",
      "search",
      {
        "input": "jql",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096
        },
        "flag": "--jql",
        "required": true
      },
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      "--json"
    ],
    "properties": {
      "jql": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4096
      },
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      }
    },
    "required": [
      "jql"
    ]
  },
  "jira-workitem-keys": {
    "path": [
      "jira",
      "workitem",
      "keys"
    ],
    "description": "Read the keys of every work item matching JQL, paginating through all results.",
    "argv": [
      "jira",
      "workitem",
      "search",
      {
        "input": "jql",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096
        },
        "flag": "--jql",
        "required": true
      },
      "--paginate",
      "--fields",
      "key,summary",
      "--json"
    ],
    "transform": "jiraWorkitemKeys",
    "maxBuffer": 8388608,
    "properties": {
      "jql": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4096
      }
    },
    "required": [
      "jql"
    ]
  },
  "jira-project-list": {
    "path": [
      "jira",
      "project",
      "list"
    ],
    "description": "Read at most 100 visible Jira projects.",
    "argv": [
      "jira",
      "project",
      "list",
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      "--json"
    ],
    "properties": {
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      }
    },
    "required": []
  },
  "jira-project-view": {
    "path": [
      "jira",
      "project",
      "view"
    ],
    "description": "Read one Jira project.",
    "argv": [
      "jira",
      "project",
      "view",
      {
        "input": "key",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Z][A-Z0-9_]*$"
        },
        "flag": "--key",
        "required": true
      },
      "--json"
    ],
    "properties": {
      "key": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Z][A-Z0-9_]*$"
      }
    },
    "required": [
      "key"
    ]
  },
  "jira-workitem-comment-list": {
    "path": [
      "jira",
      "workitem",
      "comment",
      "list"
    ],
    "description": "Read one bounded page of work item comments.",
    "argv": [
      "jira",
      "workitem",
      "comment",
      "list",
      {
        "input": "key",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Z][A-Z0-9_]*-[0-9]+$"
        },
        "flag": "--key",
        "required": true
      },
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      "--json"
    ],
    "properties": {
      "key": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Z][A-Z0-9_]*-[0-9]+$"
      },
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      }
    },
    "required": [
      "key"
    ]
  },
  "jira-workitem-attachment-list": {
    "path": [
      "jira",
      "workitem",
      "attachment",
      "list"
    ],
    "description": "Read attachment metadata without downloading files.",
    "argv": [
      "jira",
      "workitem",
      "attachment",
      "list",
      {
        "input": "key",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Z][A-Z0-9_]*-[0-9]+$"
        },
        "flag": "--key",
        "required": true
      },
      "--json"
    ],
    "properties": {
      "key": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Z][A-Z0-9_]*-[0-9]+$"
      }
    },
    "required": [
      "key"
    ]
  },
  "jira-workitem-link-list": {
    "path": [
      "jira",
      "workitem",
      "link",
      "list"
    ],
    "description": "Read links for one work item.",
    "argv": [
      "jira",
      "workitem",
      "link",
      "list",
      {
        "input": "key",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Z][A-Z0-9_]*-[0-9]+$"
        },
        "flag": "--key",
        "required": true
      },
      "--json"
    ],
    "properties": {
      "key": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Z][A-Z0-9_]*-[0-9]+$"
      }
    },
    "required": [
      "key"
    ]
  },
  "jira-workitem-list-watchers": {
    "path": [
      "jira",
      "workitem",
      "list-watchers"
    ],
    "description": "Read watchers for one work item.",
    "argv": [
      "jira",
      "workitem",
      "list-watchers",
      {
        "input": "key",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Z][A-Z0-9_]*-[0-9]+$"
        },
        "flag": "--key",
        "required": true
      },
      "--json"
    ],
    "properties": {
      "key": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Z][A-Z0-9_]*-[0-9]+$"
      }
    },
    "required": [
      "key"
    ]
  },
  "jira-board-search": {
    "path": [
      "jira",
      "board",
      "search"
    ],
    "description": "Read at most 100 boards, optionally matching a name or type.",
    "argv": [
      "jira",
      "board",
      "search",
      {
        "input": "name",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096
        },
        "flag": "--name",
        "required": false
      },
      {
        "input": "type",
        "schema": {
          "type": "string",
          "enum": [
            "scrum",
            "kanban",
            "simple"
          ]
        },
        "flag": "--type",
        "required": false
      },
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      "--json"
    ],
    "properties": {
      "name": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4096
      },
      "type": {
        "type": "string",
        "enum": [
          "scrum",
          "kanban",
          "simple"
        ]
      },
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      }
    },
    "required": []
  },
  "jira-board-view": {
    "path": [
      "jira",
      "board",
      "view"
    ],
    "description": "Read one Jira board.",
    "argv": [
      "jira",
      "board",
      "view",
      {
        "input": "id",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        },
        "flag": "--id",
        "required": true
      },
      "--json"
    ],
    "properties": {
      "id": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      }
    },
    "required": [
      "id"
    ]
  }
};
export function commandFor(actionId, input) {
  const spec = Object.hasOwn(commands, actionId) ? commands[actionId] : void 0;
  if (!spec)
    throw Error("Unsupported CLI action.");
  if (!input || typeof input !== "object" || Array.isArray(input))
    throw Error("Input must be an object.");
  if (Object.keys(input).some((key) => !Object.hasOwn(spec.properties, key)) || spec.required.some((key) => !Object.hasOwn(input, key)))
    throw Error("Unexpected or missing input field.");
  for (const [key, value] of Object.entries(input)) {
    const s = spec.properties[key];
    if (!(s.type === "integer" ? Number.isInteger(value) && value >= s.minimum && value <= s.maximum : typeof value === "string" && !value.includes("\x00") && (s.minLength === void 0 || [...value].length >= s.minLength) && (s.maxLength === void 0 || [...value].length <= s.maxLength) && (!s.pattern || new RegExp(s.pattern).test(value)) && (!s.enum || s.enum.includes(value))))
      throw Error(`Invalid input field: ${key}.`);
  }
  return { args: spec.argv.flatMap((binding) => {
    if (typeof binding === "string")
      return [binding];
    const value = input[binding.input] ?? binding.default;
    if (value === void 0)
      return [];
    return binding.flag ? [`${binding.flag}=${value}`] : [String(value)];
  }), text: spec.text === !0 };
}
function diagnosticText(result, secrets, limit) {
  if (result.error)
    return `CLI diagnostic unavailable (${result.error.code ?? "capture_failed"}).`;
  const redacted = redactSensitiveText(result.stderr ?? "", secrets).trim();
  return redacted.length > limit ? `${redacted.slice(0, limit)}\u2026 [truncated]` : redacted;
}
export function adfToMarkdown(document) {
  if (document === null || document === void 0)
    return "";
  if (typeof document === "string")
    return document.trim();
  const list = (value) => Array.isArray(value) ? value : [], inlineTypes = ["text", "hardBreak", "mention", "emoji", "inlineCard"], markOrder = ["code", "strike", "em", "strong", "link"], inline = (nodes) => list(nodes).map((node) => {
    if (!node || typeof node !== "object")
      return "";
    const attrs = node.attrs ?? {};
    switch (node.type) {
      case "text":
        return list(node.marks).filter((mark) => markOrder.includes(mark?.type)).sort((a, b) => markOrder.indexOf(a.type) - markOrder.indexOf(b.type)).reduce((text, mark) => {
          if (mark.type === "code")
            return `\`${text}\``;
          if (mark.type === "strike")
            return `~~${text}~~`;
          if (mark.type === "em")
            return `*${text}*`;
          if (mark.type === "strong")
            return `**${text}**`;
          return typeof mark.attrs?.href === "string" ? `[${text}](${mark.attrs.href})` : text;
        }, typeof node.text === "string" ? node.text : "");
      case "hardBreak":
        return `
`;
      case "mention":
        return String(attrs.text ?? "");
      case "emoji":
        return String(attrs.text || attrs.shortName || "");
      case "inlineCard":
        return String(attrs.url ?? "");
      case "media":
      case "mediaSingle":
      case "mediaGroup":
      case "mediaInline":
        return "";
      default:
        return inline(node.content);
    }
  }).join(""), blocks = (nodes, separator = `

`) => {
    const parts = [];
    let run = [];
    const flush = () => {
      if (run.length)
        parts.push(inline(run));
      run = [];
    };
    for (const node of list(nodes)) {
      if (inlineTypes.includes(node?.type)) {
        run.push(node);
        continue;
      }
      flush();
      parts.push(block(node));
    }
    flush();
    return parts.filter((part) => part.trim() !== "").join(separator);
  }, items = (node) => {
    let number = Number.isInteger(node.attrs?.order) ? node.attrs.order : 1;
    return list(node.content).map((item) => {
      const marker = node.type === "orderedList" ? `${number++}. ` : "- ", pad = " ".repeat(marker.length);
      return blocks(item?.type === "listItem" ? item.content : [item], `
`).split(`
`).map((line, index) => index === 0 ? marker + line : line ? pad + line : "").join(`
`);
    }).join(`
`);
  }, quote = (text) => text ? text.split(`
`).map((line) => line ? `> ${line}` : ">").join(`
`) : "", table = (node) => {
    const rows = list(node.content).filter((row) => row?.type === "tableRow").map((row) => list(row.content).map((cell) => blocks(cell?.content, " ").replace(/\s*\n\s*/g, " ").replace(/\|/g, "\\|").trim()));
    if (!rows.length)
      return "";
    const width = Math.max(1, ...rows.map((row) => row.length)), line = (cells) => `| ${Array.from({ length: width }, (_, index) => cells[index] ?? "").join(" | ")} |`;
    return [line(rows[0]), line(Array(width).fill("---")), ...rows.slice(1).map(line)].join(`
`);
  }, block = (node) => {
    if (!node || typeof node !== "object")
      return "";
    const attrs = node.attrs ?? {};
    switch (node.type) {
      case "paragraph":
        return inline(node.content);
      case "heading":
        return `${"#".repeat(Math.min(Math.max(Number.isInteger(attrs.level) ? attrs.level : 1, 1), 6))} ${inline(node.content)}`;
      case "bulletList":
      case "orderedList":
        return items(node);
      case "codeBlock":
        return `\`\`\`${typeof attrs.language === "string" ? attrs.language : ""}
${list(node.content).map((child) => typeof child?.text === "string" ? child.text : "").join("")}
\`\`\``;
      case "blockquote":
      case "panel":
        return quote(blocks(node.content));
      case "rule":
        return "---";
      case "blockCard":
      case "embedCard":
        return String(attrs.url ?? "");
      case "table":
        return table(node);
      case "media":
      case "mediaSingle":
      case "mediaGroup":
        return "";
      default:
        return blocks(node.content);
    }
  };
  return block(document).trim();
}
function jiraWorkitemKeys(data) {
  if (!Array.isArray(data))
    throw Error("Expected a work item array.");
  return { keys: data.map((item) => {
    if (typeof item?.key !== "string")
      throw Error("Work item is missing its key.");
    return item.key;
  }) };
}
function jiraWorkitemImport(data) {
  const fields = data?.fields;
  if (!data || typeof data !== "object" || Array.isArray(data) || typeof data.key !== "string" || !fields || typeof fields !== "object" || Array.isArray(fields) || typeof fields.summary !== "string")
    throw Error("Unexpected work item shape.");
  const name = (value) => typeof value?.name === "string" ? value.name : null, jiraType = name(fields.issuetype), jiraPriority = name(fields.priority), type = jiraType?.toLowerCase(), priorities = { highest: 1, high: 2, medium: 3, low: 4, lowest: 5 }, priority = jiraPriority?.toLowerCase();
  return {
    key: data.key,
    title: fields.summary,
    type: ["bug", "story", "epic", "spike"].includes(type) ? type : "task",
    jiraType,
    priority: priority && Object.hasOwn(priorities, priority) ? priorities[priority] : null,
    jiraPriority,
    labels: Array.isArray(fields.labels) ? fields.labels.filter((label) => typeof label === "string") : [],
    status: name(fields.status),
    descriptionMarkdown: adfToMarkdown(fields.description)
  };
}
const transforms = { jiraWorkitemKeys, jiraWorkitemImport };
export function transformOutput(actionId, data) {
  const transform = commands[actionId].transform;
  return transform ? transforms[transform](data) : data;
}
function main() {
  const fail = (code, message, termination = {}) => ({ ok: !1, error: { code, message, ...termination } });
  try {
    const bytes = readFileSync(0);
    if (bytes.length > 65536)
      return fail("invalid_input", "Request exceeds 65536 bytes.");
    const request = JSON.parse(bytes.toString("utf8")), allowed = ["protocolVersion", "toolId", "toolRevision", "action", "input", "operationId", "attemptId"];
    if (!request || request.protocolVersion !== 1 || request.toolId !== `valdr-tools.user.${cli}` || request.toolRevision !== revision || !["operationId", "attemptId"].every((key) => typeof request[key] === "string" && request[key].length > 0) || Object.keys(request).some((key) => !allowed.includes(key)))
      return fail("invalid_request", "Invalid user-tool request envelope.");
    const command = commandFor(request.action, request.input), result = spawnSync(cli, command.args, {
      encoding: "utf8",
      shell: !1,
      timeout: 25000,
      maxBuffer: commands[request.action].maxBuffer ?? 524288,
      env: { ...process.env, ...environment },
      stdio: ["ignore", "pipe", "pipe"]
    });
    if (result.error?.code === "ENOENT")
      return fail("runtime_missing", `${cli} is not installed on the host PATH.`);
    if (result.error || result.status !== 0) {
      const secrets = Object.entries(process.env).filter(([key]) => /api[_-]?key|access[_-]?key|private[_-]?key|token|secret|authorization|auth|password|credential/i.test(key)).map(([, value]) => value).filter(Boolean), details = [`${cli} failed (${result.error?.code ?? result.status ?? result.signal}).`];
      if (!result.error && failureDiagnostic && failureDiagnostic.actionPathPrefix.every((part, index) => commands[request.action].path[index] === part)) {
        const probe = spawnSync(cli, failureDiagnostic.args, { encoding: "utf8", shell: !1, timeout: 5000, maxBuffer: 16384, env: { ...process.env, ...environment }, stdio: ["ignore", "ignore", "pipe"] });
        if (probe.error || probe.status !== 0)
          details.push(`Authentication diagnostic: ${diagnosticText(probe, secrets, 600) || `status check failed (${probe.error?.code ?? probe.status ?? probe.signal}).`}`);
      }
      details.push(diagnosticText(result, secrets, 1200));
      return fail("cli_failed", details.filter(Boolean).join(`
`).slice(0, 2000), { exitCode: result.status, signal: result.signal });
    }
    try {
      return { ok: !0, data: command.text ? { version: result.stdout.trim() } : transformOutput(request.action, JSON.parse(result.stdout)) };
    } catch {
      return fail("invalid_output", `${cli} did not return valid JSON.`);
    }
  } catch (error) {
    return fail("invalid_input", error instanceof SyntaxError ? "Request must be JSON." : error.message);
  }
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) process.stdout.write(JSON.stringify(main()) + '\n');
