// Generated by scripts/generate-user-workflow-cli-tools.mjs. Edit its authoring definitions.
import { readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';

export const revision = "1.0.5";
const cli = "gh";
const environment = {
  "GH_PROMPT_DISABLED": "1",
  "GH_NO_UPDATE_NOTIFIER": "1",
  "GH_NO_EXTENSION_UPDATE_NOTIFIER": "1",
  "GH_TELEMETRY": "0",
  "GH_PAGER": "cat",
  "PAGER": "cat",
  "NO_COLOR": "1"
};
const failureDiagnostic = null;
// Generated from Valdr packages/util/src/redaction.ts; refresh via the CLI generator.
const SENSITIVE_VALUE_PATTERN = /\b(?:sk|pk|rk)[_-][a-z0-9._-]{16,}|\b(?:gh[pousr]|github_pat|xox[baprs]?)[_-][a-z0-9._-]{12,}|\b(?:ctx7|ya29)[a-z0-9._-]{12,}/gi;
const SENSITIVE_ASSIGNMENT_PATTERN = /(\b[\w.-]*(?:api[_-]?key|access[_-]?key|private[_-]?key|token|secret|authorization|password|credential)[\w.-]*\b\s*[:=]\s*)(?:"[^"]*"|'[^']*'|bearer\s+[^\s,;]+|[^\s,;]+)/gi;
const BEARER_VALUE_PATTERN = /(\bbearer\s+)[^\s,;]+/gi;
const redactSensitiveText = (value, knownSecrets = []) => {
  if (value.length === 0) {
    return value;
  }
  let scrubbed = value;
  for (const secret of new Set(knownSecrets)) {
    if (secret && secret !== "[REDACTED]")
      scrubbed = scrubbed.replaceAll(secret, "[REDACTED]");
  }
  const keyValuePattern = /("([^"]*(?:api[_-]?key|access[_-]?key|private[_-]?key|token|secret|authorization|auth|password|credential)[^"]*)"\s*:\s*")([^"]+)(")/gi;
  return scrubbed.replace(keyValuePattern, "$1[REDACTED]$4").replace(SENSITIVE_ASSIGNMENT_PATTERN, "$1[REDACTED]").replace(BEARER_VALUE_PATTERN, "$1[REDACTED]").replace(SENSITIVE_VALUE_PATTERN, "[REDACTED]");
};

export const commands = {
  "version": {
    "path": [
      "version"
    ],
    "description": "Read the installed CLI version without signing in.",
    "argv": [
      "--version"
    ],
    "text": true,
    "properties": {},
    "required": []
  },
  "repo-view": {
    "path": [
      "repo",
      "view"
    ],
    "description": "Read a repository; omit repo to use the execution working directory.",
    "argv": [
      "repo",
      "view",
      {
        "input": "repo",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
        },
        "required": false
      },
      "--json",
      "nameWithOwner,url,description,defaultBranchRef,isPrivate"
    ],
    "properties": {
      "repo": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
      }
    },
    "required": []
  },
  "repo-list": {
    "path": [
      "repo",
      "list"
    ],
    "description": "List at most 100 repositories for an owner or the authenticated user.",
    "argv": [
      "repo",
      "list",
      {
        "input": "owner",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
        },
        "required": false
      },
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      "--json",
      "nameWithOwner,url,description,isPrivate"
    ],
    "properties": {
      "owner": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
      },
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      }
    },
    "required": []
  },
  "pr-list": {
    "path": [
      "pr",
      "list"
    ],
    "description": "List at most 100 pull requests, optionally filtered by state, branch or search.",
    "argv": [
      "pr",
      "list",
      {
        "input": "repo",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
        },
        "flag": "--repo",
        "required": false
      },
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      {
        "input": "state",
        "schema": {
          "type": "string",
          "enum": [
            "open",
            "closed",
            "merged",
            "all"
          ]
        },
        "flag": "--state",
        "required": false,
        "default": "open"
      },
      {
        "input": "base",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
        },
        "flag": "--base",
        "required": false
      },
      {
        "input": "head",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
        },
        "flag": "--head",
        "required": false
      },
      {
        "input": "search",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096
        },
        "flag": "--search",
        "required": false
      },
      "--json",
      "number,title,state,url,headRefName,baseRefName"
    ],
    "properties": {
      "repo": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
      },
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      },
      "state": {
        "type": "string",
        "enum": [
          "open",
          "closed",
          "merged",
          "all"
        ]
      },
      "base": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
      },
      "head": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
      },
      "search": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4096
      }
    },
    "required": []
  },
  "pr-view": {
    "path": [
      "pr",
      "view"
    ],
    "description": "Read one pull request.",
    "argv": [
      "pr",
      "view",
      {
        "input": "number",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        },
        "required": true
      },
      {
        "input": "repo",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
        },
        "flag": "--repo",
        "required": false
      },
      "--json",
      "number,title,state,url,headRefName,baseRefName,body,author,mergeable"
    ],
    "properties": {
      "number": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "repo": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
      }
    },
    "required": [
      "number"
    ]
  },
  "issue-list": {
    "path": [
      "issue",
      "list"
    ],
    "description": "List at most 100 issues, optionally filtered by state, assignee, label or search.",
    "argv": [
      "issue",
      "list",
      {
        "input": "repo",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
        },
        "flag": "--repo",
        "required": false
      },
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      {
        "input": "state",
        "schema": {
          "type": "string",
          "enum": [
            "open",
            "closed",
            "all"
          ]
        },
        "flag": "--state",
        "required": false,
        "default": "open"
      },
      {
        "input": "assignee",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
        },
        "flag": "--assignee",
        "required": false
      },
      {
        "input": "label",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096
        },
        "flag": "--label",
        "required": false
      },
      {
        "input": "search",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096
        },
        "flag": "--search",
        "required": false
      },
      "--json",
      "number,title,state,url"
    ],
    "properties": {
      "repo": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
      },
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      },
      "state": {
        "type": "string",
        "enum": [
          "open",
          "closed",
          "all"
        ]
      },
      "assignee": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
      },
      "label": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4096
      },
      "search": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4096
      }
    },
    "required": []
  },
  "issue-view": {
    "path": [
      "issue",
      "view"
    ],
    "description": "Read one issue.",
    "argv": [
      "issue",
      "view",
      {
        "input": "number",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        },
        "required": true
      },
      {
        "input": "repo",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
        },
        "flag": "--repo",
        "required": false
      },
      "--json",
      "number,title,state,url,body,author,labels,assignees"
    ],
    "properties": {
      "number": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "repo": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
      }
    },
    "required": [
      "number"
    ]
  },
  "run-list": {
    "path": [
      "run",
      "list"
    ],
    "description": "List at most 100 Actions workflow runs.",
    "argv": [
      "run",
      "list",
      {
        "input": "repo",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
        },
        "flag": "--repo",
        "required": false
      },
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      {
        "input": "branch",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
        },
        "flag": "--branch",
        "required": false
      },
      {
        "input": "workflow",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
        },
        "flag": "--workflow",
        "required": false
      },
      "--json",
      "databaseId,displayTitle,status,conclusion,url,headBranch,workflowName"
    ],
    "properties": {
      "repo": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
      },
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      },
      "branch": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
      },
      "workflow": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
      }
    },
    "required": []
  },
  "run-view": {
    "path": [
      "run",
      "view"
    ],
    "description": "Read one Actions workflow run without downloading logs or artifacts.",
    "argv": [
      "run",
      "view",
      {
        "input": "runId",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        },
        "required": true
      },
      {
        "input": "repo",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
        },
        "flag": "--repo",
        "required": false
      },
      "--json",
      "databaseId,displayTitle,status,conclusion,url,headBranch,workflowName,jobs"
    ],
    "properties": {
      "runId": {
        "type": "integer",
        "minimum": 1,
        "maximum": 9007199254740991
      },
      "repo": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
      }
    },
    "required": [
      "runId"
    ]
  },
  "workflow-list": {
    "path": [
      "workflow",
      "list"
    ],
    "description": "List at most 100 Actions workflow definitions.",
    "argv": [
      "workflow",
      "list",
      {
        "input": "repo",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
        },
        "flag": "--repo",
        "required": false
      },
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      "--json",
      "id,name,path,state"
    ],
    "properties": {
      "repo": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
      },
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      }
    },
    "required": []
  },
  "release-list": {
    "path": [
      "release",
      "list"
    ],
    "description": "List at most 100 releases.",
    "argv": [
      "release",
      "list",
      {
        "input": "repo",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
        },
        "flag": "--repo",
        "required": false
      },
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      "--json",
      "tagName,name,isDraft,isPrerelease,publishedAt"
    ],
    "properties": {
      "repo": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
      },
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      }
    },
    "required": []
  },
  "release-view": {
    "path": [
      "release",
      "view"
    ],
    "description": "Read a release by tag, or the latest release when tag is omitted.",
    "argv": [
      "release",
      "view",
      {
        "input": "tag",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
        },
        "required": false
      },
      {
        "input": "repo",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
        },
        "flag": "--repo",
        "required": false
      },
      "--json",
      "tagName,name,body,url,isDraft,isPrerelease,publishedAt,assets"
    ],
    "properties": {
      "tag": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:/@+-]*$"
      },
      "repo": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
      }
    },
    "required": []
  },
  "label-list": {
    "path": [
      "label",
      "list"
    ],
    "description": "List at most 100 repository labels.",
    "argv": [
      "label",
      "list",
      {
        "input": "repo",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
        },
        "flag": "--repo",
        "required": false
      },
      {
        "input": "limit",
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 100
        },
        "flag": "--limit",
        "required": false,
        "default": 30
      },
      {
        "input": "search",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096
        },
        "flag": "--search",
        "required": false
      },
      "--json",
      "name,description,color"
    ],
    "properties": {
      "repo": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256,
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.-]*/[A-Za-z0-9_.-]+$"
      },
      "limit": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      },
      "search": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4096
      }
    },
    "required": []
  }
};
export function commandFor(actionId, input) {
  const spec = Object.hasOwn(commands, actionId) ? commands[actionId] : void 0;
  if (!spec)
    throw Error("Unsupported CLI action.");
  if (!input || typeof input !== "object" || Array.isArray(input))
    throw Error("Input must be an object.");
  if (Object.keys(input).some((key) => !Object.hasOwn(spec.properties, key)) || spec.required.some((key) => !Object.hasOwn(input, key)))
    throw Error("Unexpected or missing input field.");
  for (const [key, value] of Object.entries(input)) {
    const s = spec.properties[key];
    if (!(s.type === "integer" ? Number.isInteger(value) && value >= s.minimum && value <= s.maximum : typeof value === "string" && !value.includes("\x00") && (s.minLength === void 0 || [...value].length >= s.minLength) && (s.maxLength === void 0 || [...value].length <= s.maxLength) && (!s.pattern || new RegExp(s.pattern).test(value)) && (!s.enum || s.enum.includes(value))))
      throw Error(`Invalid input field: ${key}.`);
  }
  return { args: spec.argv.flatMap((binding) => {
    if (typeof binding === "string")
      return [binding];
    const value = input[binding.input] ?? binding.default;
    if (value === void 0)
      return [];
    return binding.flag ? [`${binding.flag}=${value}`] : [String(value)];
  }), text: spec.text === !0 };
}
function diagnosticText(result, secrets, limit) {
  if (result.error)
    return `CLI diagnostic unavailable (${result.error.code ?? "capture_failed"}).`;
  const redacted = redactSensitiveText(result.stderr ?? "", secrets).trim();
  return redacted.length > limit ? `${redacted.slice(0, limit)}\u2026 [truncated]` : redacted;
}
function main() {
  const fail = (code, message, termination = {}) => ({ ok: !1, error: { code, message, ...termination } });
  try {
    const bytes = readFileSync(0);
    if (bytes.length > 65536)
      return fail("invalid_input", "Request exceeds 65536 bytes.");
    const request = JSON.parse(bytes.toString("utf8")), allowed = ["protocolVersion", "toolId", "toolRevision", "action", "input", "operationId", "attemptId"];
    if (!request || request.protocolVersion !== 1 || request.toolId !== `valdr-tools.user.${cli}` || request.toolRevision !== revision || !["operationId", "attemptId"].every((key) => typeof request[key] === "string" && request[key].length > 0) || Object.keys(request).some((key) => !allowed.includes(key)))
      return fail("invalid_request", "Invalid user-tool request envelope.");
    const command = commandFor(request.action, request.input), result = spawnSync(cli, command.args, {
      encoding: "utf8",
      shell: !1,
      timeout: 25000,
      maxBuffer: 524288,
      env: { ...process.env, ...environment },
      stdio: ["ignore", "pipe", "pipe"]
    });
    if (result.error?.code === "ENOENT")
      return fail("runtime_missing", `${cli} is not installed on the host PATH.`);
    if (result.error || result.status !== 0) {
      const secrets = Object.entries(process.env).filter(([key]) => /api[_-]?key|access[_-]?key|private[_-]?key|token|secret|authorization|auth|password|credential/i.test(key)).map(([, value]) => value).filter(Boolean), details = [`${cli} failed (${result.error?.code ?? result.status ?? result.signal}).`];
      if (!result.error && failureDiagnostic && failureDiagnostic.actionPathPrefix.every((part, index) => commands[request.action].path[index] === part)) {
        const probe = spawnSync(cli, failureDiagnostic.args, { encoding: "utf8", shell: !1, timeout: 5000, maxBuffer: 16384, env: { ...process.env, ...environment }, stdio: ["ignore", "ignore", "pipe"] });
        if (probe.error || probe.status !== 0)
          details.push(`Authentication diagnostic: ${diagnosticText(probe, secrets, 600) || `status check failed (${probe.error?.code ?? probe.status ?? probe.signal}).`}`);
      }
      details.push(diagnosticText(result, secrets, 1200));
      return fail("cli_failed", details.filter(Boolean).join(`
`).slice(0, 2000), { exitCode: result.status, signal: result.signal });
    }
    try {
      return { ok: !0, data: command.text ? { version: result.stdout.trim() } : JSON.parse(result.stdout) };
    } catch {
      return fail("invalid_output", `${cli} did not return valid JSON.`);
    }
  } catch (error) {
    return fail("invalid_input", error instanceof SyntaxError ? "Request must be JSON." : error.message);
  }
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) process.stdout.write(JSON.stringify(main()) + '\n');
